In [1]:
import tensorflow as tf

In [2]:
import numpy as np

In [18]:
_x = np.asarray([[[1], [3]], [[4], [2]]])
_y = np.asarray([[1], [1]])

In [28]:
x = tf.placeholder(dtype=tf.float32, shape=[None, 2, 1])
y = tf.placeholder(dtype=tf.float32, shape=[None, 1, 1])

In [20]:
net = tf.InteractiveSession()

/home/anunnaki/anaconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py:1711: UserWarning: An interactive session is already active. This can cause out-of-memory errors in some cases. You must explicitly call `InteractiveSession.close()` to release resources held by the other session(s).
  warnings.warn('An interactive session is already active. This can '


In [29]:

net.run(tf.global_variables_initializer())

In [31]:
x.get_shape()

TensorShape([Dimension(None), Dimension(2), Dimension(1)])

In [68]:
x1 = tf.tile(x, [1, 2, 1])
net.run(x1, feed_dict={x:_x})

array([[[1.],
        [3.],
        [1.],
        [3.]],

       [[4.],
        [2.],
        [4.],
        [2.]]], dtype=float32)

In [57]:
a = tf.constant([[30, 29, 19, 17, 12, 11],
   [30, 27, 20, 16,  5,  1],
   [28, 25, 17, 14,  7,  2],
   [28, 26, 21, 14,  6,  4]], dtype=tf.int32)
a = tf.expand_dims(a, axis=0)
net.run(a)

array([[[30, 29, 19, 17, 12, 11],
        [30, 27, 20, 16,  5,  1],
        [28, 25, 17, 14,  7,  2],
        [28, 26, 21, 14,  6,  4]]], dtype=int32)

In [66]:
z = tf.shape(x1)[0]

In [67]:
net.run(z, feed_dict={x:_x})

2

In [73]:
x2 = np.asarray([[[1, 2, 3]], [[1, 2, 1]]])
x3 = np.asarray([[1, 2, 3]])
y = tf.divide(x2, x3)


In [74]:
y

array([[[1.        , 1.        , 1.        ]],

       [[1.        , 1.        , 0.33333333]]])

In [75]:
y_ = tf.convert_to_tensor(y)

In [76]:
y_

<tf.Tensor 'Const_5:0' shape=(2, 1, 3) dtype=float64>

In [78]:
net.run(y_)

array([[[1.        , 1.        , 1.        ]],

       [[1.        , 1.        , 0.33333333]]])

In [80]:
y_.get_shape()

TensorShape([Dimension(2), Dimension(1), Dimension(3)])